set search_path to "bar_app", public;

create table if not exists "tax_ride_templates" (
    "id" bigint generated by default as identity primary key,
    "tenant_id" bigint not null,
    "template_code" varchar(60) not null default 'DEFAULT',
    "template_name" varchar(120) not null default 'InsightVision RIDE',
    "layout_json" text,
    "html_content" text,
    "custom" boolean not null default false,
    "active" boolean not null default true,
    "created_at" timestamp not null default current_timestamp,
    "updated_at" timestamp not null default current_timestamp,
    constraint "fk_tax_ride_templates_tenant"
        foreign key ("tenant_id") references "erp_tenants" ("id")
);

create unique index if not exists "uk_tax_ride_templates_tenant_code"
    on "tax_ride_templates" ("tenant_id", "template_code");

create index if not exists "idx_tax_ride_templates_tenant_active"
    on "tax_ride_templates" ("tenant_id", "active");
