set search_path to "bar_app", public;

alter table "tax_documents"
    add column if not exists "ride_pdf_path" varchar(500);

alter table "tax_documents"
    add column if not exists "ride_pdf_url" varchar(500);

alter table "tax_documents"
    add column if not exists "ride_pdf_generated_at" timestamp;

alter table "tax_documents"
    add column if not exists "ride_email_status" varchar(30);

alter table "tax_documents"
    add column if not exists "ride_email_sent_at" timestamp;

alter table "tax_documents"
    add column if not exists "ride_email_error" text;

alter table "tax_sri_settings"
    add column if not exists "retention_agent" boolean not null default false;

alter table "tax_sri_settings"
    add column if not exists "retention_agent_resolution" varchar(80);

create table if not exists "tenant_email_settings" (
    "id" bigint generated by default as identity primary key,
    "tenant_id" bigint not null,
    "from_name" varchar(120),
    "from_email" varchar(180),
    "reply_to_email" varchar(180),
    "smtp_host" varchar(180),
    "smtp_port" integer default 587,
    "smtp_username" varchar(180),
    "smtp_password_encrypted" text,
    "smtp_encryption_salt" varchar(80),
    "smtp_auth" boolean not null default true,
    "smtp_starttls" boolean not null default true,
    "active" boolean not null default true,
    "created_at" timestamp not null default current_timestamp,
    "updated_at" timestamp not null default current_timestamp,
    constraint "fk_tenant_email_settings_tenant"
        foreign key ("tenant_id") references "erp_tenants" ("id")
);

create unique index if not exists "uk_tenant_email_settings_tenant"
    on "tenant_email_settings" ("tenant_id");
