set search_path to "bar_app", public;

create table if not exists "vision_api_keys" (
    "id" bigint generated by default as identity primary key,
    "tenant_id" bigint not null,
    "name" varchar(150) not null,
    "key_prefix" varchar(30) not null,
    "key_hash" varchar(128) not null,
    "status" varchar(20) not null default 'ACTIVE',
    "last_used_at" timestamp with time zone,
    "expires_at" timestamp with time zone,
    "created_at" timestamp with time zone not null default current_timestamp,
    "updated_at" timestamp with time zone not null default current_timestamp,
    "revoked_at" timestamp with time zone,
    "created_by" bigint,
    constraint "fk_vision_api_keys_tenant"
        foreign key ("tenant_id") references "erp_tenants" ("id") on delete cascade,
    constraint "fk_vision_api_keys_created_by"
        foreign key ("created_by") references "users" ("id") on delete set null,
    constraint "chk_vision_api_keys_status"
        check ("status" in ('ACTIVE', 'INACTIVE', 'REVOKED')),
    constraint "uk_vision_api_keys_hash" unique ("key_hash")
);

create index if not exists "idx_vision_api_keys_tenant_status"
    on "vision_api_keys" ("tenant_id", "status");

create index if not exists "idx_vision_api_keys_prefix"
    on "vision_api_keys" ("key_prefix");

create table if not exists "vision_cameras" (
    "id" bigint generated by default as identity primary key,
    "tenant_id" bigint not null,
    "branch_id" bigint,
    "code" varchar(80) not null,
    "name" varchar(180) not null,
    "description" text,
    "stream_url" text,
    "external_device_id" varchar(150),
    "status" varchar(30) not null default 'ACTIVE',
    "metadata" jsonb not null default '{}'::jsonb,
    "created_at" timestamp with time zone not null default current_timestamp,
    "updated_at" timestamp with time zone not null default current_timestamp,
    constraint "fk_vision_cameras_tenant"
        foreign key ("tenant_id") references "erp_tenants" ("id") on delete cascade,
    constraint "fk_vision_cameras_branch"
        foreign key ("branch_id") references "erp_branches" ("id") on delete set null,
    constraint "chk_vision_cameras_status"
        check ("status" in ('ACTIVE', 'INACTIVE', 'MAINTENANCE'))
);

create unique index if not exists "uk_vision_cameras_tenant_code"
    on "vision_cameras" ("tenant_id", lower("code"));

create index if not exists "idx_vision_cameras_tenant_status"
    on "vision_cameras" ("tenant_id", "status");

create index if not exists "idx_vision_cameras_tenant_branch"
    on "vision_cameras" ("tenant_id", "branch_id");

create index if not exists "idx_vision_cameras_metadata_gin"
    on "vision_cameras" using gin ("metadata");

create table if not exists "vision_events" (
    "id" bigint generated by default as identity primary key,
    "tenant_id" bigint not null,
    "camera_id" bigint not null,
    "branch_id" bigint,
    "event_timestamp" timestamp with time zone not null,
    "received_at" timestamp with time zone not null default current_timestamp,
    "frame_id" varchar(180),
    "idempotency_key" varchar(250),
    "source" varchar(120) not null default 'yolo-service',
    "model_name" varchar(120),
    "model_version" varchar(120),
    "confidence_threshold" numeric(5,4),
    "image_width" integer,
    "image_height" integer,
    "image_uri" text,
    "total_detections" integer not null default 0,
    "status" varchar(30) not null default 'RECEIVED',
    "processing_ms" integer,
    "metadata" jsonb not null default '{}'::jsonb,
    "created_at" timestamp with time zone not null default current_timestamp,
    "updated_at" timestamp with time zone not null default current_timestamp,
    constraint "fk_vision_events_tenant"
        foreign key ("tenant_id") references "erp_tenants" ("id") on delete cascade,
    constraint "fk_vision_events_camera"
        foreign key ("camera_id") references "vision_cameras" ("id") on delete restrict,
    constraint "fk_vision_events_branch"
        foreign key ("branch_id") references "erp_branches" ("id") on delete set null,
    constraint "chk_vision_events_status"
        check ("status" in ('RECEIVED', 'PROCESSED', 'DUPLICATED', 'FAILED')),
    constraint "chk_vision_events_total_detections"
        check ("total_detections" >= 0),
    constraint "chk_vision_events_image_width"
        check ("image_width" is null or "image_width" > 0),
    constraint "chk_vision_events_image_height"
        check ("image_height" is null or "image_height" > 0)
);

create unique index if not exists "uk_vision_events_tenant_idempotency"
    on "vision_events" ("tenant_id", "idempotency_key")
    where "idempotency_key" is not null;

create unique index if not exists "uk_vision_events_tenant_camera_frame"
    on "vision_events" ("tenant_id", "camera_id", "frame_id")
    where "frame_id" is not null;

create index if not exists "idx_vision_events_tenant_camera_time"
    on "vision_events" ("tenant_id", "camera_id", "event_timestamp" desc);

create index if not exists "idx_vision_events_tenant_branch_time"
    on "vision_events" ("tenant_id", "branch_id", "event_timestamp" desc);

create index if not exists "idx_vision_events_tenant_time"
    on "vision_events" ("tenant_id", "event_timestamp" desc);

create index if not exists "idx_vision_events_status"
    on "vision_events" ("status");

create index if not exists "idx_vision_events_metadata_gin"
    on "vision_events" using gin ("metadata");

create table if not exists "vision_detections" (
    "id" bigint generated by default as identity primary key,
    "tenant_id" bigint not null,
    "event_id" bigint not null,
    "camera_id" bigint not null,
    "branch_id" bigint,
    "label" varchar(120) not null,
    "confidence" numeric(6,5) not null,
    "bbox_x" numeric(12,4) not null,
    "bbox_y" numeric(12,4) not null,
    "bbox_width" numeric(12,4) not null,
    "bbox_height" numeric(12,4) not null,
    "tracking_id" varchar(180),
    "metadata" jsonb not null default '{}'::jsonb,
    "created_at" timestamp with time zone not null default current_timestamp,
    constraint "fk_vision_detections_tenant"
        foreign key ("tenant_id") references "erp_tenants" ("id") on delete cascade,
    constraint "fk_vision_detections_event"
        foreign key ("event_id") references "vision_events" ("id") on delete cascade,
    constraint "fk_vision_detections_camera"
        foreign key ("camera_id") references "vision_cameras" ("id") on delete restrict,
    constraint "fk_vision_detections_branch"
        foreign key ("branch_id") references "erp_branches" ("id") on delete set null,
    constraint "chk_vision_detections_confidence"
        check ("confidence" >= 0 and "confidence" <= 1),
    constraint "chk_vision_detections_bbox_width"
        check ("bbox_width" > 0),
    constraint "chk_vision_detections_bbox_height"
        check ("bbox_height" > 0)
);

create index if not exists "idx_vision_detections_tenant_event"
    on "vision_detections" ("tenant_id", "event_id");

create index if not exists "idx_vision_detections_tenant_camera_label"
    on "vision_detections" ("tenant_id", "camera_id", "label");

create index if not exists "idx_vision_detections_tenant_label_created"
    on "vision_detections" ("tenant_id", "label", "created_at" desc);

create index if not exists "idx_vision_detections_tenant_branch_label"
    on "vision_detections" ("tenant_id", "branch_id", "label");

create index if not exists "idx_vision_detections_metadata_gin"
    on "vision_detections" using gin ("metadata");

create table if not exists "vision_statistics_hourly" (
    "id" bigint generated by default as identity primary key,
    "tenant_id" bigint not null,
    "camera_id" bigint not null,
    "branch_id" bigint,
    "label" varchar(120) not null,
    "period_start" timestamp with time zone not null,
    "period_end" timestamp with time zone not null,
    "total_events" integer not null default 0,
    "total_detections" integer not null default 0,
    "confidence_sum" numeric(18,6) not null default 0,
    "avg_confidence" numeric(8,5),
    "max_confidence" numeric(8,5),
    "min_confidence" numeric(8,5),
    "created_at" timestamp with time zone not null default current_timestamp,
    "updated_at" timestamp with time zone not null default current_timestamp,
    constraint "fk_vision_stats_hourly_tenant"
        foreign key ("tenant_id") references "erp_tenants" ("id") on delete cascade,
    constraint "fk_vision_stats_hourly_camera"
        foreign key ("camera_id") references "vision_cameras" ("id") on delete cascade,
    constraint "fk_vision_stats_hourly_branch"
        foreign key ("branch_id") references "erp_branches" ("id") on delete set null,
    constraint "chk_vision_stats_hourly_totals"
        check ("total_events" >= 0 and "total_detections" >= 0)
);

create unique index if not exists "uk_vision_stats_hourly_scope"
    on "vision_statistics_hourly" ("tenant_id", "camera_id", "branch_id", "label", "period_start")
    nulls not distinct;

create index if not exists "idx_vision_stats_hourly_tenant_period"
    on "vision_statistics_hourly" ("tenant_id", "period_start" desc, "period_end" desc);

create index if not exists "idx_vision_stats_hourly_tenant_camera_period"
    on "vision_statistics_hourly" ("tenant_id", "camera_id", "period_start" desc);

create index if not exists "idx_vision_stats_hourly_tenant_label_period"
    on "vision_statistics_hourly" ("tenant_id", "label", "period_start" desc);

create table if not exists "vision_statistics_daily" (
    "id" bigint generated by default as identity primary key,
    "tenant_id" bigint not null,
    "camera_id" bigint not null,
    "branch_id" bigint,
    "label" varchar(120) not null,
    "period_date" date not null,
    "total_events" integer not null default 0,
    "total_detections" integer not null default 0,
    "confidence_sum" numeric(18,6) not null default 0,
    "avg_confidence" numeric(8,5),
    "max_confidence" numeric(8,5),
    "min_confidence" numeric(8,5),
    "created_at" timestamp with time zone not null default current_timestamp,
    "updated_at" timestamp with time zone not null default current_timestamp,
    constraint "fk_vision_stats_daily_tenant"
        foreign key ("tenant_id") references "erp_tenants" ("id") on delete cascade,
    constraint "fk_vision_stats_daily_camera"
        foreign key ("camera_id") references "vision_cameras" ("id") on delete cascade,
    constraint "fk_vision_stats_daily_branch"
        foreign key ("branch_id") references "erp_branches" ("id") on delete set null,
    constraint "chk_vision_stats_daily_totals"
        check ("total_events" >= 0 and "total_detections" >= 0)
);

create unique index if not exists "uk_vision_stats_daily_scope"
    on "vision_statistics_daily" ("tenant_id", "camera_id", "branch_id", "label", "period_date")
    nulls not distinct;

create index if not exists "idx_vision_stats_daily_tenant_period"
    on "vision_statistics_daily" ("tenant_id", "period_date" desc);

create index if not exists "idx_vision_stats_daily_tenant_camera_period"
    on "vision_statistics_daily" ("tenant_id", "camera_id", "period_date" desc);

create index if not exists "idx_vision_stats_daily_tenant_label_period"
    on "vision_statistics_daily" ("tenant_id", "label", "period_date" desc);

create table if not exists "vision_statistics_monthly" (
    "id" bigint generated by default as identity primary key,
    "tenant_id" bigint not null,
    "camera_id" bigint not null,
    "branch_id" bigint,
    "label" varchar(120) not null,
    "period_month" date not null,
    "total_events" integer not null default 0,
    "total_detections" integer not null default 0,
    "confidence_sum" numeric(18,6) not null default 0,
    "avg_confidence" numeric(8,5),
    "max_confidence" numeric(8,5),
    "min_confidence" numeric(8,5),
    "created_at" timestamp with time zone not null default current_timestamp,
    "updated_at" timestamp with time zone not null default current_timestamp,
    constraint "fk_vision_stats_monthly_tenant"
        foreign key ("tenant_id") references "erp_tenants" ("id") on delete cascade,
    constraint "fk_vision_stats_monthly_camera"
        foreign key ("camera_id") references "vision_cameras" ("id") on delete cascade,
    constraint "fk_vision_stats_monthly_branch"
        foreign key ("branch_id") references "erp_branches" ("id") on delete set null,
    constraint "chk_vision_stats_monthly_totals"
        check ("total_events" >= 0 and "total_detections" >= 0)
);

create unique index if not exists "uk_vision_stats_monthly_scope"
    on "vision_statistics_monthly" ("tenant_id", "camera_id", "branch_id", "label", "period_month")
    nulls not distinct;

create index if not exists "idx_vision_stats_monthly_tenant_period"
    on "vision_statistics_monthly" ("tenant_id", "period_month" desc);

create index if not exists "idx_vision_stats_monthly_tenant_camera_period"
    on "vision_statistics_monthly" ("tenant_id", "camera_id", "period_month" desc);

create index if not exists "idx_vision_stats_monthly_tenant_label_period"
    on "vision_statistics_monthly" ("tenant_id", "label", "period_month" desc);

create table if not exists "vision_alerts" (
    "id" bigint generated by default as identity primary key,
    "tenant_id" bigint not null,
    "camera_id" bigint,
    "branch_id" bigint,
    "label" varchar(120),
    "severity" varchar(30) not null default 'INFO',
    "message" text not null,
    "status" varchar(30) not null default 'OPEN',
    "created_at" timestamp with time zone not null default current_timestamp,
    "resolved_at" timestamp with time zone,
    constraint "fk_vision_alerts_tenant"
        foreign key ("tenant_id") references "erp_tenants" ("id") on delete cascade,
    constraint "fk_vision_alerts_camera"
        foreign key ("camera_id") references "vision_cameras" ("id") on delete set null,
    constraint "fk_vision_alerts_branch"
        foreign key ("branch_id") references "erp_branches" ("id") on delete set null
);

create index if not exists "idx_vision_alerts_tenant_status"
    on "vision_alerts" ("tenant_id", "status", "created_at" desc);

create table if not exists "vision_processing_logs" (
    "id" bigint generated by default as identity primary key,
    "tenant_id" bigint not null,
    "event_id" bigint,
    "camera_id" bigint,
    "level" varchar(20) not null default 'INFO',
    "code" varchar(80),
    "message" text not null,
    "metadata" jsonb not null default '{}'::jsonb,
    "created_at" timestamp with time zone not null default current_timestamp,
    constraint "fk_vision_processing_logs_tenant"
        foreign key ("tenant_id") references "erp_tenants" ("id") on delete cascade,
    constraint "fk_vision_processing_logs_event"
        foreign key ("event_id") references "vision_events" ("id") on delete set null,
    constraint "fk_vision_processing_logs_camera"
        foreign key ("camera_id") references "vision_cameras" ("id") on delete set null
);

create index if not exists "idx_vision_processing_logs_tenant_created"
    on "vision_processing_logs" ("tenant_id", "created_at" desc);

create table if not exists "vision_webhook_logs" (
    "id" bigint generated by default as identity primary key,
    "tenant_id" bigint,
    "provider" varchar(80) not null default 'YOLO',
    "event_id" bigint,
    "idempotency_key" varchar(250),
    "status" varchar(30) not null,
    "request_headers" jsonb not null default '{}'::jsonb,
    "payload_json" jsonb not null default '{}'::jsonb,
    "response_code" varchar(80),
    "response_message" text,
    "created_at" timestamp with time zone not null default current_timestamp,
    constraint "fk_vision_webhook_logs_tenant"
        foreign key ("tenant_id") references "erp_tenants" ("id") on delete set null,
    constraint "fk_vision_webhook_logs_event"
        foreign key ("event_id") references "vision_events" ("id") on delete set null
);

create index if not exists "idx_vision_webhook_logs_tenant_created"
    on "vision_webhook_logs" ("tenant_id", "created_at" desc);

create table if not exists "vision_audit_logs" (
    "id" bigint generated by default as identity primary key,
    "tenant_id" bigint not null,
    "user_id" bigint,
    "action" varchar(100) not null,
    "resource_type" varchar(80) not null,
    "resource_id" bigint,
    "ip_address" varchar(80),
    "metadata" jsonb not null default '{}'::jsonb,
    "created_at" timestamp with time zone not null default current_timestamp,
    constraint "fk_vision_audit_logs_tenant"
        foreign key ("tenant_id") references "erp_tenants" ("id") on delete cascade,
    constraint "fk_vision_audit_logs_user"
        foreign key ("user_id") references "users" ("id") on delete set null
);

create index if not exists "idx_vision_audit_logs_tenant_created"
    on "vision_audit_logs" ("tenant_id", "created_at" desc);

create or replace function "vision_touch_updated_at"()
returns trigger
language plpgsql
as $$
begin
    new."updated_at" = current_timestamp;
    return new;
end;
$$;

drop trigger if exists "trg_vision_api_keys_updated_at" on "vision_api_keys";
create trigger "trg_vision_api_keys_updated_at"
    before update on "vision_api_keys"
    for each row execute function "vision_touch_updated_at"();

drop trigger if exists "trg_vision_cameras_updated_at" on "vision_cameras";
create trigger "trg_vision_cameras_updated_at"
    before update on "vision_cameras"
    for each row execute function "vision_touch_updated_at"();

drop trigger if exists "trg_vision_events_updated_at" on "vision_events";
create trigger "trg_vision_events_updated_at"
    before update on "vision_events"
    for each row execute function "vision_touch_updated_at"();

drop trigger if exists "trg_vision_stats_hourly_updated_at" on "vision_statistics_hourly";
create trigger "trg_vision_stats_hourly_updated_at"
    before update on "vision_statistics_hourly"
    for each row execute function "vision_touch_updated_at"();

drop trigger if exists "trg_vision_stats_daily_updated_at" on "vision_statistics_daily";
create trigger "trg_vision_stats_daily_updated_at"
    before update on "vision_statistics_daily"
    for each row execute function "vision_touch_updated_at"();

drop trigger if exists "trg_vision_stats_monthly_updated_at" on "vision_statistics_monthly";
create trigger "trg_vision_stats_monthly_updated_at"
    before update on "vision_statistics_monthly"
    for each row execute function "vision_touch_updated_at"();
