set search_path to "bar_app", public;

alter table "tax_documents"
    add column if not exists "ride_email_last_attempt_at" timestamp with time zone;

alter table "tax_documents"
    add column if not exists "ride_email_provider" varchar(40);

alter table "tax_documents"
    add column if not exists "ride_email_message_id" varchar(180);

alter table "tax_documents"
    add column if not exists "ride_email_template_code" varchar(80);

create table if not exists "invoice_email_logs" (
    "id" bigint generated by default as identity primary key,
    "tenant_id" bigint not null,
    "tax_document_id" bigint not null,
    "attempt_number" integer not null default 1,
    "provider" varchar(40) not null,
    "provider_message_id" varchar(180),
    "from_email" varchar(180) not null,
    "from_name" varchar(180),
    "reply_to_email" varchar(180),
    "to_email" varchar(180) not null,
    "subject" varchar(300) not null,
    "template_code" varchar(80) not null,
    "status" varchar(40) not null default 'PENDING',
    "error_code" varchar(120),
    "error_message" text,
    "retryable" boolean not null default false,
    "attachment_count" integer not null default 0,
    "attachment_total_bytes" bigint not null default 0,
    "sent_at" timestamp with time zone,
    "delivered_at" timestamp with time zone,
    "bounced_at" timestamp with time zone,
    "complained_at" timestamp with time zone,
    "opened_at" timestamp with time zone,
    "clicked_at" timestamp with time zone,
    "created_at" timestamp with time zone not null default current_timestamp,
    "updated_at" timestamp with time zone not null default current_timestamp,
    constraint "fk_invoice_email_logs_tenant"
        foreign key ("tenant_id") references "erp_tenants" ("id") on delete cascade,
    constraint "fk_invoice_email_logs_document"
        foreign key ("tax_document_id") references "tax_documents" ("id") on delete cascade,
    constraint "chk_invoice_email_logs_attempt"
        check ("attempt_number" > 0),
    constraint "chk_invoice_email_logs_attachments"
        check ("attachment_count" >= 0 and "attachment_total_bytes" >= 0)
);

create index if not exists "idx_invoice_email_logs_tenant_document"
    on "invoice_email_logs" ("tenant_id", "tax_document_id", "created_at" desc);

create index if not exists "idx_invoice_email_logs_tenant_status_created"
    on "invoice_email_logs" ("tenant_id", "status", "created_at" desc);

create index if not exists "idx_invoice_email_logs_tenant_created"
    on "invoice_email_logs" ("tenant_id", "created_at" desc);

create index if not exists "idx_invoice_email_logs_provider_message"
    on "invoice_email_logs" ("provider_message_id")
    where "provider_message_id" is not null;

create table if not exists "resend_webhook_events" (
    "id" bigint generated by default as identity primary key,
    "tenant_id" bigint,
    "event_type" varchar(120),
    "provider_message_id" varchar(180),
    "signature_valid" boolean not null default false,
    "payload_json" jsonb not null default '{}'::jsonb,
    "headers_json" jsonb not null default '{}'::jsonb,
    "status" varchar(40) not null default 'RECEIVED',
    "error_message" text,
    "received_at" timestamp with time zone not null default current_timestamp,
    "processed_at" timestamp with time zone,
    constraint "fk_resend_webhook_events_tenant"
        foreign key ("tenant_id") references "erp_tenants" ("id") on delete set null
);

create index if not exists "idx_resend_webhook_events_message"
    on "resend_webhook_events" ("provider_message_id");

create index if not exists "idx_resend_webhook_events_tenant_received"
    on "resend_webhook_events" ("tenant_id", "received_at" desc);

create table if not exists "email_templates" (
    "id" bigint generated by default as identity primary key,
    "tenant_id" bigint,
    "template_code" varchar(80) not null,
    "version" integer not null default 1,
    "subject" varchar(300) not null,
    "html_body" text not null,
    "active" boolean not null default true,
    "created_by" bigint,
    "created_at" timestamp with time zone not null default current_timestamp,
    "updated_at" timestamp with time zone not null default current_timestamp,
    constraint "fk_email_templates_tenant"
        foreign key ("tenant_id") references "erp_tenants" ("id") on delete cascade,
    constraint "fk_email_templates_created_by"
        foreign key ("created_by") references "users" ("id") on delete set null
);

create unique index if not exists "uk_email_templates_tenant_code_version"
    on "email_templates" ("tenant_id", "template_code", "version")
    nulls not distinct;

create index if not exists "idx_email_templates_tenant_code_active"
    on "email_templates" ("tenant_id", "template_code", "active");

insert into "email_templates" ("tenant_id", "template_code", "version", "subject", "html_body", "active")
values
    (null, 'SRI_INVOICE_ISSUED', 1,
     'Factura electronica {{documentNumber}}',
     '<div style="font-family:Arial,sans-serif;color:#172033;line-height:1.5"><h2 style="margin:0 0 12px;color:#123a5a">Factura electronica autorizada</h2><p>Hola {{customerName}}, adjuntamos el XML autorizado y el RIDE de tu factura.</p><table style="border-collapse:collapse;margin-top:12px"><tr><td style="padding:4px 12px 4px 0"><strong>Emisor</strong></td><td>{{issuerName}}</td></tr><tr><td style="padding:4px 12px 4px 0"><strong>RUC</strong></td><td>{{issuerRuc}}</td></tr><tr><td style="padding:4px 12px 4px 0"><strong>Numero</strong></td><td>{{documentNumber}}</td></tr><tr><td style="padding:4px 12px 4px 0"><strong>Fecha</strong></td><td>{{issueDate}}</td></tr><tr><td style="padding:4px 12px 4px 0"><strong>Total</strong></td><td>{{totalAmount}}</td></tr><tr><td style="padding:4px 12px 4px 0"><strong>Autorizacion</strong></td><td>{{authorizationNumber}}</td></tr></table><p style="font-size:12px;color:#536173;margin-top:18px">Soporte: {{supportEmail}}</p></div>',
     true),
    (null, 'SRI_INVOICE_RESEND', 1,
     'Reenvio de factura electronica {{documentNumber}}',
     '<div style="font-family:Arial,sans-serif;color:#172033;line-height:1.5"><h2 style="margin:0 0 12px;color:#123a5a">Reenvio de factura electronica</h2><p>Hola {{customerName}}, reenviamos el XML autorizado y el RIDE de tu factura.</p><p><strong>Factura:</strong> {{documentNumber}}<br><strong>Total:</strong> {{totalAmount}}<br><strong>Autorizacion:</strong> {{authorizationNumber}}</p><p style="font-size:12px;color:#536173;margin-top:18px">Soporte: {{supportEmail}}</p></div>',
     true),
    (null, 'SRI_INVOICE_SEND_FAILED_ADMIN', 1,
     'Fallo envio factura {{documentNumber}}',
     '<div style="font-family:Arial,sans-serif;color:#172033;line-height:1.5"><h2 style="margin:0 0 12px;color:#8a1f11">Fallo el envio de una factura</h2><p>No se pudo enviar la factura {{documentNumber}} al cliente {{customerEmail}}.</p><p>Revisa el historial de correos del documento y la configuracion del proveedor.</p></div>',
     true)
on conflict ("tenant_id", "template_code", "version") do nothing;

create or replace function "invoice_email_touch_updated_at"()
returns trigger
language plpgsql
as $$
begin
    new."updated_at" = current_timestamp;
    return new;
end;
$$;

drop trigger if exists "trg_invoice_email_logs_updated_at" on "invoice_email_logs";
create trigger "trg_invoice_email_logs_updated_at"
    before update on "invoice_email_logs"
    for each row execute function "invoice_email_touch_updated_at"();

drop trigger if exists "trg_email_templates_updated_at" on "email_templates";
create trigger "trg_email_templates_updated_at"
    before update on "email_templates"
    for each row execute function "invoice_email_touch_updated_at"();
